version: '3.5'

services:
  metrics-collector:
    image: ${DOCKER_IMAGE}
    restart: on-failure:3
    depends_on:
      - kafka
      - zookeeper
      - postgres
    environment:
      JAVA_OPTS: -Dconfig.resource=docker.conf -Dlogback.configurationFile=logback.xml -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
